//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Project.rc
//
#define DLG_MISENVIOS                   9
#define DLG_START                       101
#define IDR_MENU1                       102
#define DLG_REGISTRO                    104
#define DLG_FIRST                       106
#define DLG_NUEVOENVIO                  115
#define DLG_NUEVOPRODUCTO               117
#define DLG_ELIMINARPRODUCTO            119
#define DLG_EDITARPROD                  121
#define DLG_SALIR                       123
#define DLG_CANCELARENVIO               125
#define DLG_EDITARENVIO                 127
#define DLG_COMPRAR                     129
#define BTN_ST_INICIO                   1001
#define TXT_R_USUARIO                   1003
#define TXT_R_PASSWORD                  1004
#define STC_PASSWORD                    1006
#define STC_USUARIO                     1007
#define BTN_ST_REGISTRO                 1008
#define BTN_R_REGRESAR                  1010
#define BTN_R_REGISTRAR                 1011
#define TXT_F_NOMBRE                    1012
#define IMG_ELP_FOTO                    1013
#define TXT_F_EMPRESA                   1014
#define IMG_ELP_FOTO2                   1015
#define TXT_EE_CANTIDAD                 1018
#define TXT_EE_CANT                     1018
#define TXT_EE_TOTAL                    1019
#define TXT_EE_COLONIA                  1020
#define TXT_EE_CALLE                    1021
#define TXT_EE_ESTADO                   1022
#define TXT_EE_MENSAJE                  1023
#define DTP_EE_FECHA                    1024
#define TXT_ELP_DESCRIPCION             1024
#define STC_CE_PRODUCTO                 1025
#define TXT_ELP_COSTO                   1026
#define TXT_EE_CIUDAD                   1027
#define BTN_EP_GUARDAR                  1027
#define TXT_ELP_CANT                    1029
#define TXT_ELP_CODIGO                  1030
#define TXT_ELP_MARCA                   1031
#define BTN_ELP_CONF                    1035
#define TXT_ELP_BUSQUEDA                1036
#define BTN_S_CANCELAR                  1038
#define BTN_S_SALIR                     1039
#define BTN_CE_ELIMINAR                 1045
#define STC_ST_DATE                     1049
#define TXT_CE_CANT                     1050
#define TXT_CE_CALLE                    1051
#define TXT_CE_COLONIA                  1052
#define TXT_CE_ESTADO                   1053
#define TXT_CE_MENSAJE                  1054
#define DTP_CE_FECHA                    1055
#define TXT_CE_TOTAL                    1056
#define TXT_CE_CIUDAD                   1057
#define TXT_ST_USUARIO                  1058
#define TXT_ST_PASSWORD                 1059
#define LIST_C_PRODUCTOS                1060
#define IMG_C_FOTO                      1062
#define IMG_C_FOTO2                     1063
#define TXT_C_COSTO                     1064
#define TXT_C_DESCRIPCION               1065
#define TXT_C_MARCA                     1066
#define TXT_C_CODIGO                    1067
#define TXT_C_CANT                      1068
#define TXT_C_PRODUCTO                  1069
#define BTN_C_COMPRAR                   1070
#define STC_C_DATE                      1071
#define STC_C_USUARIO                   1072
#define TXT_NP_PRODUCTO                 1072
#define TXT_NP_CANT                     1073
#define TXT_NP_CODIGO                   1074
#define TXT_NP_MARCA                    1075
#define TXT_NP_DESCRIPCION              1076
#define TXT_NP_COSTO                    1077
#define IMG_NP_FOTO                     1078
#define IMG_NP_FOTO2                    1079
#define BTN_NP_GUARDAR                  1080
#define BTN_NP_REGRESAR                 1081
#define IMG_F_FOTO                      1081
#define BTN_F_GUARDAR                   1082
#define STC_F_DATE                      1083
#define STC_F_USUARIO                   1084
#define STC_NE_PRODUCTO                 1084
#define TXT_NE_TOTAL                    1085
#define TXT_NE_CANT                     1086
#define TXT_NE_CALLE                    1087
#define TXT_NE_COLONIA                  1088
#define TXT_NE_ESTADO                   1089
#define TXT_NE_MENSAJE                  1090
#define DTP_NE_FECHA                    1091
#define BTN_NE_CONF                     1092
#define STC_NE_USUARIO                  1093
#define STC_NE_DATE                     1094
#define TXT_NE_CIUDAD                   1095
#define TXT_NP_CIUDAD                   1096
#define BTN_NE_REGRESAR                 1097
#define BTN_EE_GUARDAR                  1098
#define STC_EE_DATE                     1099
#define STC_EE_USUARIO                  1100
#define BTN_EE_REGRESAR                 1101
#define STC_CIUDAD                      1102
#define LIST_CE_ENVIOS                  1103
#define STC_CE_USUARIO                  1104
#define STC_CE_DATE                     1105
#define BTN_CE_REGRESAR                 1106
#define STC_ME_DATE                     1107
#define STC_ME_USUARIO                  1108
#define STC_ME_PRODUCTO                 1109
#define TXT_ME_CANT                     1110
#define TXT_ME_TOTAL                    1111
#define TXT_ME_CALLE                    1112
#define TXT_ME_COLONIA                  1113
#define TXT_ME_CIUDAD                   1114
#define TXT_ME_ESTADO                   1115
#define TXT_ME_MENSAJE                  1116
#define DTP_ME_FECHA                    1117
#define BTN_ME_REGRESAR                 1118
#define LIST_ME_ENVIOS                  1119
#define STC_EE_PRODUCTO                 1120
#define TXT_EP_BUSQUEDA                 1121
#define TXT_EP_PRODUCTO                 1122
#define TXT_EP_CANT                     1123
#define TXT_EP_CODIGO                   1124
#define TXT_EP_MARCA                    1125
#define TXT_EP_DESCRIPCION              1126
#define TXT_EP_COSTO                    1127
#define IMG_EP_FOTO                     1128
#define IMG_EP_FOTO2                    1129
#define STC_EP_DATE                     1130
#define STC_EP_USUARIO                  1131
#define BTN_EP_BUSCAR                   1132
#define BTN_ELP_BUSCAR                  1133
#define BTN_EP_REGRESAR                 1134
#define STC_ELP_DATE                    1135
#define STC_ELP_USUARIO                 1136
#define TXT_ELP_PRODUCTO                1137
#define BTN_ELP_REGRESAR                1138
#define LIST_EE_ENVIOS                  1139
#define ID_PRODUCTOS_LISTADETODOSLOSPRODUCTOS 40001
#define ID_ENV40002                     40002
#define ID_ENV40003                     40003
#define ID_ENV40004                     40004
#define ID_ENV40005                     40005
#define ID_ENV40006                     40006
#define ID_ENV40007                     40007
#define ID_BUTTON2                      40008
#define ID_PRODUCTOS_NUEVOPRODUCTO      40009
#define ID_PRODUCTOS_ELIMINARPRODUCTO   40010
#define ID_PRODUCTOS_EDITARPRODUCTO     40011
#define ID_PRODUCTOS_MISPRODUCTOS       40012
#define ID_INFORMACI40013               40013
#define ID_SALIR                        40014
#define ID_ENVIO_COMPRAR                40015
#define ID_ENVIO_CANCELAR               40016
#define ID_ENVIO_EDITAR                 40017
#define ID_ENVIO_MISENVIOS              40018
#define ID_INFORMACION                  40019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         40020
#define _APS_NEXT_CONTROL_VALUE         1140
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
